dismiss:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: binary_sensor
          multiple: true

undismiss:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: binary_sensor
          multiple: true

mute:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: binary_sensor
          multiple: true

unmute:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: binary_sensor
          multiple: true

disable:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: binary_sensor
          multiple: true

enable:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: binary_sensor
          multiple: true

cleanup:
  fields:
    orphans:
      required: false
      default: false
      selector:
        boolean:

export_journal:
  fields:
    since:
      required: false
      selector:
        datetime:
    until:
      required: false
      selector:
        datetime:
    entity_id:
      required: false
      selector:
        entity:
          domain: binary_sensor
